import { drawInt } from '../core/rng.ts';
import { illegal, type Game } from '../core/types.ts';

const W = 8, H = 8, N = W * H, BOXES = 2;
const DIRS: Record<string, number> = { up: -W, down: W, left: -1, right: 1 };
const NAMES = Object.keys(DIRS);
interface Level { walls: Uint8Array; targets: number[]; start: { player: number; boxes: number[] }; dist: Map<number, number>; optimal: number }
export interface SokobanState { seed: number; player: number; boxes: number[]; moves: number }

const key = (player: number, boxes: number[]) => { const [a, b] = boxes[0] < boxes[1] ? boxes : [boxes[1], boxes[0]]; return player + N * (a + N * b); };
const solvedBy = (boxes: number[], targets: number[]) => boxes.every((b) => targets.includes(b));

function move(walls: Uint8Array, player: number, boxes: number[], d: number): { player: number; boxes: number[] } | null {
  const to = player + d;
  if (walls[to]) return null;
  const bi = boxes.indexOf(to);
  if (bi < 0) return { player: to, boxes };
  const beyond = to + d;
  if (walls[beyond] || boxes.includes(beyond)) return null;
  const nb = boxes.slice(); nb[bi] = beyond;
  return { player: to, boxes: nb };
}

/** forward BFS over every reachable state, then reverse BFS from solved states: exact moves-to-solve for all states */
function solve(walls: Uint8Array, targets: number[], start: { player: number; boxes: number[] }) {
  const ids = new Map<number, number>(), states: { player: number; boxes: number[] }[] = [], rev: number[][] = [];
  const add = (st: { player: number; boxes: number[] }) => { const k = key(st.player, st.boxes); let i = ids.get(k); if (i === undefined) { i = states.length; ids.set(k, i); states.push(st); rev.push([]); } return i; };
  add(start);
  for (let i = 0; i < states.length && states.length < 200000; i++) {
    if (solvedBy(states[i].boxes, targets)) continue;
    for (const d of Object.values(DIRS)) { const n = move(walls, states[i].player, states[i].boxes, d); if (n) rev[add(n)].push(i); }
  }
  const dist = new Map<number, number>(), q: number[] = [];
  states.forEach((st, i) => { if (solvedBy(st.boxes, targets)) { dist.set(key(st.player, st.boxes), 0); q.push(i); } });
  const di = new Array(states.length).fill(-1); for (const i of q) di[i] = 0;
  for (let h = 0; h < q.length; h++) for (const p of rev[q[h]]) if (di[p] < 0) { di[p] = di[q[h]] + 1; dist.set(key(states[p].player, states[p].boxes), di[p]); q.push(p); }
  return dist;
}

const cache = new Map<number, Level>();
/** levels are generated by playing backwards from the solved position (pulls), so every level is solvable */
export function levelOf(seed: number): Level {
  const hit = cache.get(seed); if (hit) return hit;
  let best: Level | null = null;
  for (let attempt = 0; attempt < 40; attempt++) {
    const r = (i: number, n: number) => drawInt(seed, 5, attempt * 4096 + i, n);
    const walls = new Uint8Array(N);
    for (let p = 0; p < N; p++) { const x = p % W, y = Math.floor(p / W); if (x === 0 || y === 0 || x === W - 1 || y === H - 1) walls[p] = 1; }
    for (let i = 0; i < 5; i++) { const p = (1 + r(i, H - 2)) * W + 1 + r(50 + i, W - 2); walls[p] = 1; }
    const floor = [...Array(N).keys()].filter((p) => !walls[p]);
    const seen = new Set([floor[0]]), q = [floor[0]];
    while (q.length) { const c = q.shift()!; for (const d of Object.values(DIRS)) if (!walls[c + d] && !seen.has(c + d)) { seen.add(c + d); q.push(c + d); } }
    if (seen.size !== floor.length) continue;
    const targets: number[] = [];
    for (let i = 0; targets.length < BOXES; i++) { const p = floor[r(100 + i, floor.length)]; if (!targets.includes(p)) targets.push(p); }
    let boxes = targets.slice(), player = -1;
    for (let i = 0; player < 0; i++) { const p = floor[r(200 + i, floor.length)]; if (!boxes.includes(p)) player = p; }
    for (let k = 0; k < 240; k++) {
      const d = Object.values(DIRS)[r(300 + k, 4)], to = player + d;
      if (walls[to] || boxes.includes(to)) continue;
      const bi = boxes.indexOf(player - d);
      if (bi >= 0 && r(500 + k, 4) !== 0) { boxes = boxes.slice(); boxes[bi] = player; }
      player = to;
    }
    if (solvedBy(boxes, targets)) continue;
    const dist = solve(walls, targets, { player, boxes });
    const optimal = dist.get(key(player, boxes)) ?? Infinity;
    if (!Number.isFinite(optimal)) continue;
    const lvl = { walls, targets, start: { player, boxes }, dist, optimal };
    if (!best || optimal > best.optimal) best = lvl;
    if (optimal >= 20) break;
  }
  cache.set(seed, best!);
  return best!;
}

const onTarget = (s: SokobanState, l: Level) => s.boxes.filter((b) => l.targets.includes(b)).length;

export const sokoban: Game<SokobanState> = {
  id: 'sokoban', prefix: 'SOK', name: 'Sokoban', version: '1.0.0', realtime: null, maxSteps: 200,
  rules: 'Sokoban in an 8x8 room. Move up, down, left or right; walking into a box pushes it one cell if the cell beyond is free. Boxes cannot be pulled. Push every box onto a target. Score: one point per box on a target, plus one for solving. The game ends when solved or after 200 moves.',
  init: (seed) => { const l = levelOf(seed); return { seed, player: l.start.player, boxes: l.start.boxes.slice(), moves: 0 }; },
  legal: (s) => { const l = levelOf(s.seed); return NAMES.filter((n) => move(l.walls, s.player, s.boxes, DIRS[n])); },
  step(s, a) {
    const l = levelOf(s.seed), n = DIRS[a] !== undefined ? move(l.walls, s.player, s.boxes, DIRS[a]) : null;
    if (!n) illegal('sokoban', a, sokoban.legal(s));
    return { seed: s.seed, player: n.player, boxes: n.boxes, moves: s.moves + 1 };
  },
  done: (s) => s.moves >= sokoban.maxSteps || solvedBy(s.boxes, levelOf(s.seed).targets),
  score: (s) => { const l = levelOf(s.seed), k = onTarget(s, l); return k + (k === BOXES ? 1 : 0); },
  render(s) {
    const l = levelOf(s.seed);
    const ch = (p: number) => l.walls[p] ? '#' : s.boxes.includes(p) ? (l.targets.includes(p) ? '*' : 'B') : p === s.player ? (l.targets.includes(p) ? '+' : '@') : l.targets.includes(p) ? 'x' : '.';
    const rows = Array.from({ length: H }, (_, y) => Array.from({ length: W }, (_, x) => ch(y * W + x)).join(''));
    return `${rows.join('\n')}\n# wall, @ you, B box, x target, * box on target, + you on target. boxes on target: ${onTarget(s, l)}/${BOXES}  moves: ${s.moves}/200`;
  },
  data: (s) => { const l = levelOf(s.seed), xy = (p: number) => [p % W, Math.floor(p / W)]; return { walls: [...l.walls.keys()].filter((p) => l.walls[p]).map(xy), targets: l.targets.map(xy), boxes: s.boxes.map(xy), player: xy(s.player), moves: s.moves }; },
  label: (s, a) => { const l = levelOf(s.seed); return s.boxes.includes(s.player + DIRS[a]) ? `push ${a}` : `move ${a}`; },
  features(s, a) {
    const l = levelOf(s.seed), n = move(l.walls, s.player, s.boxes, DIRS[a])!;
    return { pushes: n.boxes !== s.boxes ? 1 : 0, boxesOnTargetAfter: n.boxes.filter((b) => l.targets.includes(b)).length };
  },
  values(s) {
    const l = levelOf(s.seed), out: Record<string, number> = {};
    for (const a of sokoban.legal(s)) { const n = move(l.walls, s.player, s.boxes, DIRS[a])!; const d = l.dist.get(key(n.player, n.boxes)); out[a] = d === undefined ? -1000 : -(1 + d); }
    return out;
  },
  valuesExact: true,
};
